<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.TemplateEngine.Authoring.TemplateVerifier" Version="10.0.302" />
        <PackageReference Include="TUnit" Version="1.6*"/>
    </ItemGroup>

</Project>
