# pack-templates.ps1
# Packages all templates into a single NuGet template pack (.nupkg).
# The package is written to artifacts/nuget_packages/.
#
# Version is read from automation/version.json if present, or defaults to 0.1.0.
# Override with -Version to specify a version explicitly.
#
# Usage:
#   .\pack-templates.ps1
#   .\pack-templates.ps1 -Version 1.2.0
#   .\pack-templates.ps1 -Version 1.2.0-beta.1

param(
    # Package version. Overrides the value in automation/version.json.
    [string]$Version = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'shared.ps1')

Initialize-OutputDirectories

$repoRoot   = Get-RepoRoot
$outputPath = Get-NugetPackagesPath
$tempCsproj = Join-Path $repoRoot '_pack-temp.csproj'

# ---------------------------------------------------------------------------
# Determine version
# ---------------------------------------------------------------------------

if (-not $Version) {
    $Version = Get-PackageVersion
}

Write-Banner "Pack Templates  (v$Version)"
Write-Info "Output : $outputPath"
Write-Info "Version: $Version"

# ---------------------------------------------------------------------------
# Ensure there is something to pack
# ---------------------------------------------------------------------------

$templates = Get-AllTemplates

if ($templates.Count -eq 0) {
    Write-Warn 'No templates found. Nothing to pack.'
    exit 0
}

Write-Step "Templates to include ($($templates.Count)):"
foreach ($t in $templates) {
    Write-Info "$($t.Type.PadRight(10)) $($t.ShortName.PadRight(30)) $($t.Identity)"
}

# ---------------------------------------------------------------------------
# Generate a temporary pack project
# ---------------------------------------------------------------------------

Write-Step 'Generating temporary pack project...'

# Build <Content> includes for each template type that exists.
$contentItems = @()
foreach ($type in @('item', 'project', 'solution')) {
    $typePath = Join-Path (Get-TemplatesRoot) $type
    if (Test-Path $typePath) {
        # Use forward slashes inside the XML to keep MSBuild happy on Windows and Linux
        $relPath = "templates/$type/**/*"
        $contentItems += "    <Content Include=`"$relPath`" Exclude=`"**/bin/**;**/obj/**;**/.vs/**;**/*.user`" />"
    }
}

$csprojContent = @"
<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Temporary pack project generated by pack-templates.ps1.
    Do not modify or commit this file.
  -->

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>Eaton.AustinKaylor.Templates</PackageId>
    <Version>$Version</Version>
    <Title>Eaton AustinKaylor Templates</Title>
    <Authors>Austin Kaylor</Authors>
    <Description>A collection of dotnet new templates for common C# patterns.</Description>
    <PackageTags>dotnet;templates;csharp;eaton</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
  </PropertyGroup>

  <ItemGroup>
$($contentItems -join "`n")
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
"@

Set-Content -Path $tempCsproj -Value $csprojContent -Encoding UTF8
Write-Success "Temporary project created at repo root."

# ---------------------------------------------------------------------------
# Pack
# ---------------------------------------------------------------------------

Write-Step 'Running dotnet pack...'

try {
    & dotnet pack $tempCsproj `
        --output $outputPath `
        --nologo `
        -p:Version=$Version 2>&1 | ForEach-Object { Write-Info $_ }

    Assert-Success $LASTEXITCODE 'dotnet pack'
}
finally {
    # Always clean up the temp project
    if (Test-Path $tempCsproj) {
        Remove-Item -Force $tempCsproj
        Write-Info 'Temporary pack project removed.'
    }
}

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

$packageFile = Get-ChildItem -Path $outputPath -Filter "Eaton.AustinKaylor.Templates.$Version.nupkg" |
    Select-Object -First 1

Write-Banner 'Pack Complete'

if ($packageFile) {
    Write-Success "Package created: $($packageFile.FullName)"
    Write-Info "Size: $([Math]::Round($packageFile.Length / 1KB, 1)) KB"
}
else {
    Write-Warn "Package file not found in $outputPath — check the dotnet pack output above."
}

Write-Host ''
Write-Info "To publish: .\publish-templates.ps1 -Version $Version"

